name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies in each workspace
        run: |
          cd shared && npm install
          cd ../studio && npm install  
          cd ../frontend && npm install

      - name: Build shared package
        run: cd shared && npm run build

      - name: Build studio package
        run: cd studio && npm run build

      - name: Build frontend package  
        run: cd frontend && npm run build
        env:
          PUBLIC_SANITY_PROJECT_ID: ${{ secrets.PUBLIC_SANITY_PROJECT_ID || 'i952bgb1' }}
          PUBLIC_SANITY_DATASET: ${{ secrets.PUBLIC_SANITY_DATASET || 'production' }}
          SANITY_STUDIO_PROJECT_ID: ${{ secrets.SANITY_STUDIO_PROJECT_ID || 'i952bgb1' }}
          SANITY_STUDIO_DATASET: ${{ secrets.SANITY_STUDIO_DATASET || 'production' }}
          SITE_URL: ${{ secrets.SITE_URL || 'https://example.com' }}
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts
          path: |
            frontend/dist
            studio/dist
            shared/dist

  # Temporarily disabled release job - focus on getting build working first
  # release:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   needs: build
  #   
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  # 
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20.x
  # 
  #     - name: Install dependencies in each workspace
  #       run: |
  #         cd shared && npm install
  #         cd ../studio && npm install  
  #         cd ../frontend && npm install
  # 
  #     - name: Create Release Pull Request
  #       uses: changesets/action@v1
  #       with:
  #         publish: npx changeset publish
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}